# Generated by Django 5.0.2 on 2024-02-21 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ESTADUAL', 'ESTADUAL'), ('NACIONAL', 'NACIONAL'), ('INTERNACIONAL', 'INTERNACIONAL')], max_length=13)),
                ('categoria', models.CharField(choices=[('COPA', 'COPA'), ('CAMPEONATO', 'CAMPEONATO')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='')),
                ('clube', models.CharField(max_length=255)),
                ('posicao_principal', models.CharField(max_length=255)),
                ('numero_camisa', models.IntegerField(default=0)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TituloCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ClubeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
                ('ano_fund', models.DateField(verbose_name='Ano de Fundação')),
                ('divisao_atual', models.CharField(choices=[('A', 'Serie A'), ('B', 'Serie B'), ('C', 'Serie C'), ('D', 'Serie D')], default='B', max_length=1)),
                ('escudo_clube', models.ImageField(upload_to='', verbose_name='Escudo')),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255, verbose_name='País')),
                ('categoria', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('jogadores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jogador')),
                ('titulos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.titulocompeticao')),
            ],
        ),
    ]
