# Generated by Django 5.0.2 on 2024-02-27 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubeTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('ano_fund', models.PositiveIntegerField(verbose_name='Ano de Fundação')),
                ('divisao_atual', models.CharField(choices=[('A', 'Serie A'), ('B', 'Serie B'), ('C', 'Serie C'), ('D', 'Serie D')], default='A', max_length=1)),
                ('escudo_clube', models.ImageField(upload_to='img/shell', verbose_name='Escudo')),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255, verbose_name='País')),
                ('categoria', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
            ],
            options={
                'verbose_name': 'Clube/Time',
                'verbose_name_plural': 'Clubes/Times',
            },
        ),
        migrations.CreateModel(
            name='Competicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ESTADUAL', 'ESTADUAL'), ('NACIONAL', 'NACIONAL'), ('INTERNACIONAL', 'INTERNACIONAL')], default='ESTADUAL', max_length=13)),
                ('categoria', models.CharField(choices=[('COPA', 'COPA'), ('CAMPEONATO', 'CAMPEONATO')], default='COPA', max_length=10)),
            ],
            options={
                'verbose_name': 'Competição',
                'verbose_name_plural': 'Competições',
            },
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='img/gamer')),
                ('posicao_principal', models.CharField(max_length=255)),
                ('numero_camisa', models.PositiveIntegerField(default=1)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1)),
                ('clube', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.clubetime')),
            ],
            options={
                'verbose_name_plural': 'Jogadores',
            },
        ),
        migrations.AddField(
            model_name='clubetime',
            name='jogadores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.jogador'),
        ),
        migrations.CreateModel(
            name='TituloCompeticao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_conquista', models.PositiveIntegerField(default=2024, verbose_name='Ano da Conquista')),
                ('data_exata', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(choices=[('CAMPEAO', 'Campeão'), ('VICE', 'Vice')], default='CAMPEAO', max_length=7)),
                ('clube', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clubetime')),
                ('competicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competicao')),
            ],
            options={
                'verbose_name': 'Título de Competição',
                'verbose_name_plural': 'Título de Competições',
            },
        ),
        migrations.AddField(
            model_name='clubetime',
            name='titulos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.titulocompeticao'),
        ),
    ]
