# Generated by Django 5.0.2 on 2024-02-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_competicao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubetime',
            name='categoria',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='clubetime',
            name='divisao_atual',
            field=models.CharField(choices=[('A', 'Serie A'), ('B', 'Serie B'), ('C', 'Serie C'), ('D', 'Serie D')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='competicao',
            name='categoria',
            field=models.CharField(choices=[('COPA', 'COPA'), ('CAMPEONATO', 'CAMPEONATO')], default='COPA', max_length=10),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1),
        ),
    ]
