# Generated by Django 5.0.2 on 2024-02-23 10:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_clubetime_options_alter_competicao_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='titulocompeticao',
            name='ano_conquista',
            field=models.PositiveIntegerField(default=2024, verbose_name='Ano da Conquista'),
        ),
        migrations.AddField(
            model_name='titulocompeticao',
            name='clube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clubetime'),
        ),
        migrations.AddField(
            model_name='titulocompeticao',
            name='competicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.competicao'),
        ),
        migrations.AddField(
            model_name='titulocompeticao',
            name='data_exata',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='titulocompeticao',
            name='titulo',
            field=models.CharField(choices=[('CAMPEAO', 'Campeão'), ('VICE', 'Vice')], default='CAMPEAO', max_length=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clubetime',
            name='ano_fund',
            field=models.PositiveIntegerField(verbose_name='Ano de Fundação'),
        ),
        migrations.AlterField(
            model_name='clubetime',
            name='escudo_clube',
            field=models.ImageField(upload_to='img/shell', verbose_name='Escudo'),
        ),
        migrations.AlterField(
            model_name='clubetime',
            name='jogadores',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.jogador'),
        ),
        migrations.AlterField(
            model_name='clubetime',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
