# Generated by Django 5.0.2 on 2024-02-23 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_titulocompeticao_clube_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubetime',
            options={'verbose_name': 'Clube/Time', 'verbose_name_plural': 'Clubes/Times'},
        ),
        migrations.AlterModelOptions(
            name='competicao',
            options={'verbose_name': 'Competição', 'verbose_name_plural': 'Competições'},
        ),
        migrations.AlterField(
            model_name='jogador',
            name='foto',
            field=models.ImageField(upload_to='img/gamer'),
        ),
        migrations.AlterField(
            model_name='titulocompeticao',
            name='competicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.competicao', verbose_name='Competição'),
        ),
    ]
